
spring.application.name=api-gateway
server.port=9090

#this method is called static routing

# Transaction Service
spring.cloud.gateway.server.webmvc.routes[0].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/transactions/**

# Risk Score Service
spring.cloud.gateway.server.webmvc.routes[1].id=risk-score-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/risk/**

# There are 3 types of Gateways.
# 1.Framework-based Gateways (Spring Cloud Gateway, Zuul)
# 2.Cloud-based Gateways (Managed) (Amazon API Gateway, Azure API Management, Google Cloud Endpoints)
# 3.Reverse Proxy / Gateway Tools(NGINX, Kong, Traefik)