
spring.application.name=api-gateway
server.port=9090

<<<<<<< HEAD
#Euraka

=======
>>>>>>> 0775aeb438cc71f0eab59ba94932b54c684576b4
#this method is called static routing

# Transaction Service
spring.cloud.gateway.server.webmvc.routes[0].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/transactions/**

# Risk Score Service
spring.cloud.gateway.server.webmvc.routes[1].id=risk-score-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/risk/**